version: '3'

services:
  # Description of Containers:
  #
  #   authproxy   This is the oauth2_proxy container
  #   nginx       This is the reverse proxy webserver
  #   backend      This is the webapp that is protected by the oauth2_proxy

  # Azure OAuth Proxy
  authproxy:
    container_name: authproxy
    image: bitnami/oauth2-proxy:latest
    networks:
      - webapp-net
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_CLIENT_ID=<<<<REPLACE ME>>>>
      - OAUTH2_PROXY_CLIENT_SECRET=<<<<REPLACE ME>>>>
      - OAUTH2_PROXY_COOKIE_SECRET=<<<<REPLACE ME>>>>
      - OAUTH2_PROXY_COOKIE_DOMAIN=localhost
    command: [
      "--provider=azure",
      "--cookie-secure=false",
      "--upstream=http://upstream:80",
      "--http-address=0.0.0.0:4180",
      "--redirect-url=http://localhost/oauth2/callback",
      "--email-domain=turing.ac.uk",
      "--azure-tenant=<<<<REPLACE ME>>>>",
      "--session-cookie-minimal=true"
    ]

  # nginx
  upstream:
    build: nginx
    #image: azureusage/nginx:latest
    networks:
      - webapp-net
    ports:
      - "80:80"
    depends_on:
      - authproxy
      - backend

  # backend
  backend:
    build: ../.
    #image: azureusage/azure_usage:latest
    networks:
      - webapp-net
    ports:
      - "5006:5006"
    command: [
      "/webapp/RUN.sh", "5006"
    ]

networks:
  webapp-net:
    driver: bridge
